
skillMetadata:
  sections:
    - name: Sonos Node Server IP Address
      fields:
        - name: sonos_node_server_ip_explanation_label
          type: label
          label: Enter here the (local) IP Address or Hostname of your Sonos Node JS HTTP Server
        - name: sonos_server_ip
          type: text
          label: IP Address or Hostname
          value: ""

    - name: Room
      fields:
        - name: room_explanation_label
          type: label
          label: The room your Mycroft device is located in
        - name: room
          type: text
          label: room
          value: ""
